name: Test and Build

on:
  push:
    branches: ["main", "Angel"]
  pull_request:
    branches: ["main", "Angel"]

permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Checeo de la rama (el codigo)
      - name: Set up Python 3.10 #Instalar python
        uses: actions/setup-python@v4 #Todas las dependecias y cosas necesarias para ejecutar py
        with:
          python-version: '3.10'
      - name: Install dependencies #Instalar dependencias de los requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
      - name: Test with pytest #Ejecutar pruebas con pytest
        run: |
          pytest
